# example netlify.toml
[build]
  command = "next build"
  functions = "netlify/functions"
  publish = ".next"
[build.environment]
# Change this path with the path to your repository
GO_IMPORT_PATH = "https://github.com/Crevitus/nextjs-prismic-typescript-netlify-starter"

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
